name: pr_size

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Release notes check
    steps:
      - name: Check for release notes
        id: rn
        uses: richardcase/release-note-action@v0.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}